############################
## CHANGE THESE
############################

baseURL: 'https://steviecoaster.dev'
title: What the Shell?!

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


